### ISSUE TITLE
Vue.js await is a reserved word 

### ISSUE THREAD

**Issue by achiko** [dharmaprotocol/dharma.js#284]
Is this Vue.js issue?  is Dharmajs compatible with  Vue ? 

 25 |   methods: {
  26 |   	createLoanRequest: function() {
> 27 |   		const loanRequest = await LoanRequest.create(dharma, {
     |   		                    ^
  28 | 			    principalAmount: 5,
  29 | 			    principalToken: "WETH",
....

**Comment by rahulrumalla** [comment]
Fellow vuejs-er here. What is the issue/error that you're actually seeing btw?

**Comment by graemecode** [comment]
@achiko , @rahulrumalla -- could you give me a little more context? Are you seeing this when you try to create a loan request? In that case, you could use:

``` javascript
LoanRequest.create(dharma, {
  ...loanOptions,
}).then((loanRequest) => {
  // continue here...
});
```

**Comment by rahulrumalla** [comment]
I'd guess this is a misleading error by IDE plugin. I remember this message from when I missed the 'async' keyword on the function.

**Comment by graemecode** [comment]
Yes, you definitely would need to have `async` on the function to use `await`! Like so:

```javascript
(async (input) => {
  await doSomethingAsync(input);
})();
```

Closing for now, let me know if you still think this is a problem. 
Good luck!

**Comment by achiko** [comment]
Sorry for a late reply 
I have just pushed repo: https://github.com/achiko/vue-dharma 
Please look at https://github.com/achiko/vue-dharma/blob/master/src/components/Loanrequest.vue  

Now I'm getting following error: 

xml-http-request.js?37da:91 Uncaught (in promise) TypeError: Cannot read property 'node' of undefined
    at new XMLHttpRequest (xml-http-request.js?37da:91)
    at HttpProvider.prepareRequest (httpprovider.js?f85f:61)
    at HttpProvider.sendAsync (httpprovider.js?f85f:116)
    at RequestManager.sendAsync (requestmanager.js?111b:80)
    at Object.send (method.js?7c38:141)
    at eval (index.js?10a5:46)
    at new Promise (<anonymous>)
    at new F (_export.js?63b6:36)
    at eval (index.js?10a5:28)
    at BlockchainAPI.eval (blockchain_api.js?fc5b:199)
